language: generic

matrix:
  include:
    # clang-tidy/format specific job
    - os: linux
      sudo: false
      env: CLANG_FORMAT CLANG_TIDY
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
      script:
        - make tidy
        - make format
    - os: linux
      sudo: false
      env: CXX=g++-4.9
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-4.9' ]
    - os: linux
      sudo: false
      env: CXX=g++-5
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'g++-5' ]
    - os: linux
      sudo: false
      env: CXX=clang++
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
    - os: linux
      sudo: false
      env: CXXFLAGS="-fsanitize=address,undefined,integer -fno-sanitize-recover=all"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
    # coverage build
    - os: linux
      sudo: false
      env: CXXFLAGS="--coverage" LDFLAGS="--coverage"
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test' ]
          packages: [ 'libstdc++6', 'libstdc++-5-dev' ]
      script:
        - make debug
        - make test
        # MASON_LLVM_RELEASE comes from the setup.sh script
        - mason install llvm-cov ${MASON_LLVM_RELEASE}
        - mason link llvm-cov ${MASON_LLVM_RELEASE}
        - curl -S -f https://codecov.io/bash -o codecov
        - chmod +x codecov
        - ./codecov -x "llvm-cov gcov" -Z

install:
  - ./scripts/setup.sh --config local.env
  - source local.env
  - mason install build2 0.7.0-a.0.1517662481.a542a12b9195bb49
  - mason link build2 0.7.0-a.0.1517662481.a542a12b9195bb49
  - mason install catch 1.9.6
  - mason link catch 1.9.6
  - mason install benchmark 1.2.0
  - mason link benchmark 1.2.0
  - b -v config.cxx=clang++ config.cxx.coptions="-O3 -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0"
  - ./test/test
  - ./bench/run
  - b clean

script:
  - make clean
